set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CXX_FLAGS "/GL")
set(VCPKG_C_FLAGS "/GL")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    "-DFEATURE_winsdkicu:BOOL=OFF"
    "-DFEATURE_timezone:BOOL=OFF"
    "-DFEATURE_direct3d11:BOOL=OFF"
    "-DFEATURE_direct3d11_1:BOOL=OFF"
    "-DFEATURE_direct3d12:BOOL=OFF"
    "-DFEATURE_direct2d1_1:BOOL=OFF"
    "-DFEATURE_vulkan:BOOL=OFF"
    "-DFEATURE_pdf:BOOL=OFF"
    "-DFEATURE_printsupport:BOOL=OFF"
    "-DFEATURE_printer:BOOL=OFF"
    "-DFEATURE_textmarkdownreader:BOOL=OFF"
    "-DFEATURE_system_textmarkdownreader:BOOL=OFF"
    "-DFEATURE_textmarkdownwriter:BOOL=OFF"
    "-DFEATURE_textodfwriter:BOOL=OFF"
    "-DFEATURE_movie:BOOL=OFF"
    "-DFEATURE_picture:BOOL=OFF"
    "-DFEATURE_imageformat_jpeg:BOOL=OFF"
    "-DFEATURE_imageformat_bmp:BOOL=OFF"
    "-DFEATURE_imageformat_ppm:BOOL=OFF"
    "-DFEATURE_imageformat_xbm:BOOL=OFF"
    "-DFEATURE_imageformat_xpm:BOOL=OFF"
    "-DFEATURE_systemtrayicon:BOOL=OFF"
    "-DFEATURE_whatsthis:BOOL=OFF"
    "-DFEATURE_accessibility:BOOL=OFF"
    "-DFEATURE_tabletevent:BOOL=OFF"
    "-DFEATURE_emojisegmenter:BOOL=OFF"
    "-DFEATURE_fontcombobox:BOOL=OFF"
    "-DFEATURE_fontdialog:BOOL=OFF"
    "-DFEATURE_colordialog:BOOL=OFF"
    "-DFEATURE_calendarwidget:BOOL=OFF"
    "-DFEATURE_wizard:BOOL=OFF"
    "-DFEATURE_mdiarea:BOOL=OFF"
    "-DFEATURE_lcdnumber:BOOL=OFF"
    "-DFEATURE_dial:BOOL=OFF"
    "-DFEATURE_splashscreen:BOOL=OFF"
    "-DFEATURE_toolbox:BOOL=OFF"
    "-DFEATURE_columnview:BOOL=OFF"
    "-DFEATURE_undoview:BOOL=OFF"
    "-DFEATURE_keysequenceedit:BOOL=OFF"
    "-DFEATURE_commandlinkbutton:BOOL=OFF"
    "-DFEATURE_progressdialog:BOOL=OFF"
    "-DFEATURE_errormessage:BOOL=OFF"
    "-DFEATURE_datetimeedit:BOOL=OFF"
    "-DFEATURE_treewidget:BOOL=OFF"
    "-DFEATURE_textbrowser:BOOL=OFF"
    "-DFEATURE_syntaxhighlighter:BOOL=OFF"
    "-DFEATURE_sharedmemory:BOOL=OFF"
    "-DFEATURE_systemsemaphore:BOOL=OFF"
    "-DFEATURE_jalalicalendar:BOOL=OFF"
    "-DFEATURE_islamiccivilcalendar:BOOL=OFF"
    "-DFEATURE_gestures:BOOL=OFF"
    "-DFEATURE_translation:BOOL=OFF"
    "-DFEATURE_permissions:BOOL=OFF"
    "-DFEATURE_process:BOOL=OFF"
    "-DFEATURE_filesystemwatcher:BOOL=OFF"
    "-DFEATURE_concatenatetablesproxymodel:BOOL=OFF"
    "-DFEATURE_transposeproxymodel:BOOL=OFF"
    "-DFEATURE_identityproxymodel:BOOL=OFF"
)
